# Generated by Django 5.0.6 on 2024-07-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCountdownApp', '0002_remove_countdown_end_date_remove_countdown_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='event_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
