# Generated by Django 5.0.6 on 2024-07-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCountdownApp', '0003_alter_countdown_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='countdown',
            name='event_emoji',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='countdown',
            name='event_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='countdown',
            name='event_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='countdown',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
