# Generated by Django 5.0.6 on 2024-07-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCountdownApp', '0004_alter_countdown_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='event_title',
            field=models.CharField(max_length=200),
        ),
    ]
