# Generated by Django 2.2 on 2024-09-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCountdownApp', '0005_alter_countdown_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
